substitutions:
  board: esp32-s3-devkitc-1
  name: "waveshare-esp32-s3-lcd-7"
  device_description: Waveshare ESP32 S3 LCD 7'
  type: esp-idf
  s_ip: # Your device Static IP      
  latitude: ""    
  longitude: ""  
  weather_characters: " !#%'()+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWYZ[]_abcdefghijklmnopqrstuvwxyz{|}°²³µ맑음흐림대체로비뇌우안개폭호구름많동서남북알수없매좋높보통쾌적나쁨최악시눈내위험자외오존미세초먼지선월화목금토일풍데이터습도실온단양아조감건함주어제다낮요"
  allowed_characters: " !#%'()+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWYZ[]_abcdefghijklmnopqrstuvwxyz{|}°²³µ실내외거서재주방다용도화장안베란우좌측전체에어컨가습창문생시볼륨로비간접보조블라인드현설버티컬온관중등냉고송명자러수동난풍제꺼짐강약정기날씨디오메뉴너지소량사월당태양광발모일통계단남은필터취침켜공청닫힘열림면밝대절복귀출점스플레이식패턴하브리환"
  title_characters: " !#%'()+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWYZ[]_abcdefghijklmnopqrstuvwxyz{|}오전후일월화수목금토"

esp32:
  flash_size: 8MB
  partitions: "default_8MB.csv"
  
i2c:
  scl: GPIO9
  sda: GPIO8
  scan: True

#uart:
 # tx_pin: GPIO43
  #rx_pin: GPIO44
  #baud_rate: 9600

packages:
  # base
  base: !include base.yaml
  display: !include display.yaml
  fonts: !include fonts.yaml
  #pages
  menu: !include pages/menu.yaml
  weather: !include pages/weather.yaml
  climate: !include pages/climate.yaml
  blind: !include pages/blind.yaml

# LVGL CORE
lvgl:
# Default Style
  bg_color: 0
  text_font: regular_25
  align: center
# Idle Action
  on_idle:
    - timeout: !lambda return id(return_timeout).state * 1000;
      then:
        if: 
          condition:
            - light.is_on: backlight
          then:
            - lvgl.page.show: weather_page
    - timeout: !lambda return id(screen_timeout).state * 1000;
      then:
        if:
          condition:
            and:
              - light.is_on: backlight
              - binary_sensor.is_off: presence_sensor
          then:
            - light.turn_off: backlight
            
# 상단 타이틀 (Do not package)
  top_layer:
    widgets: 
      - obj:
          x: 0
          y: 0
          width: 800
          height: 30
          styles : title_bar
          widgets:
            - obj:
                width: 350
                height: 28
                styles : title_bar
                align: TOP_LEFT
                layout:
                  type: FLEX
                  flex_flow: ROW
                  flex_align_main: START
                widgets:                  
                  - label:
                      text: "오전 00:00"
                      id: title_time
                      align: TOP_LEFT
                      text_align: left
                  - label:
                      text: "\U000F001B"
                      id: aircon_run
                      hidden: true
                      align: TOP_RIGHT
                      text_align: right
                  - label:
                      text: "\U000F0F92"
                      id: boiler_run
                      hidden: true
                      align: TOP_RIGHT
                      text_align: right
                  - label:
                      text: "\U000F1099"
                      id: humidifier_run
                      hidden: true
                      align: TOP_RIGHT
                      text_align: right
                  - label:
                      text: "\U000F0D44"
                      id: purifier_run
                      hidden: true
                      align: TOP_RIGHT
                      text_align: right
                  
            - label:
                text: "2000-00-00(일)"
                id: title_date
                align: TOP_MID
                x: 0
                y: 2
                text_align: CENTER
            - obj:
                width: 350
                height: 28
                styles : title_bar
                align: TOP_RIGHT
                layout:
                  type: FLEX
                  flex_flow: ROW
                  flex_align_main: END
                widgets:
                  - label:
                      text: "\U000F192C 0 W"
                      id: energy_meter_power_title
                      align: TOP_RIGHT 
                      text_align: right
                  - label:
                      text: "\U000F1A73 0 W"
                      id: solar_power_title
                      align: TOP_RIGHT             
                      text_align: right
                  - label:
                      text: "\U000F05A9"
                      id: wifi_connected
                      hidden: true
                      align: TOP_RIGHT               
                      text_align: right
                  - label:
                      text: "\U000F16C5"
                      id: wifi_disconnected                
                      align: TOP_RIGHT
                      text_align: right

                
