substitutions:
  weather_characters: " !#%'()+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWYZ[]_abcdefghijklmnopqrstuvwxyz{|}°²³µ맑음흐림대체로비뇌우안개폭호구름많동서남북알수없매좋높보통쾌적나쁨최악시눈내위험자외오존미세초먼지선월화목금토일풍데이터습도실온단양아조감건함주어제다낮요"
  allowed_characters: " !#%'()+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWYZ[]_abcdefghijklmnopqrstuvwxyz{|}°²³µ실내외거서재주방다용도화장안베란우좌측전체에어컨가습창문생시볼륨로비간접보조블라인드현설버티컬온관중등냉고송명자러수동난풍제꺼짐강약정기날씨디오메뉴너지소량사월당태양광발모일통계단남은필터취침켜공청닫힘열림면밝대절복귀출점스플레이식패턴하브리환"
  title_characters: " !#%'()+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWYZ[]_abcdefghijklmnopqrstuvwxyz{|}오전후일월화수목금토"
# 폰트 설정
font:
  - file: "fonts/DroidSansHS.ttf"
    id: regular_20
    size: 20
    bpp: 4
    glyphs: ${allowed_characters}
  - file: "fonts/Roboto-Bold.woff"
    id: regular_25
    size: 25
    bpp: 4
    glyphs: ${allowed_characters}
    extras:
      - file: 'fonts/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
        glyphs: [
          "\U000F0769",  # mdi:ceiling-light
          "\U000F18DD",  # mdi:ceiling-light-multiple
          "\U000F179B",  # mdi:light-recessed
          "\U000F141E",  # mdi:dome-light
          "\U000F1054",  # mdi:outdoor-lamp
          "\U000F1356"  # mdi:television-ambient-light
          ]   
  - file: "fonts/Roboto-Bold.woff"
    id: regular_40
    size: 40
    bpp: 4
    glyphs: ${allowed_characters}     
    extras:
      - file: 'fonts/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
        glyphs: [
          "\U000F040A", # mdi:play
          "\U000F03E4",  # mdi:pause
          "\U000F04DB",  # mdi:stop
          "\U000F057E",  # mdi:volume-high
          "\U000F0581",  # mdi:volume-off
          "\U000F0143",  # mdi:chevron-up
          "\U000F0140",  # mdi:chevron-down
          "\U000F1A2E",  # mdi:blinds-vertical-closed
          "\U000F1A2D",  # mdi:blinds-vertical        
          "\U000F084E",  # mdi:arrow-expand-horizontal
          "\U000F084C"   # mdi:arrow-collapse-horizontal
          ]   
  - file: "fonts/DroidSansHS.ttf"
    id: weather_70
    size: 70
    bpp: 4
    glyphs: ${weather_characters}
  - file: "fonts/DroidSansHS.ttf"
    id: weather_40
    size: 35
    bpp: 4    
    glyphs: ${weather_characters}
    extras:
      - file: 'fonts/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
        glyphs: [
          "\U000F054A" # mdi:umbrella
          ]
  - file: "fonts/DroidSansHS.ttf"
    id: weather_25
    size: 25
    bpp: 4
    glyphs: ${weather_characters}
    extras:
      - file: 'fonts/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
        glyphs: [
          "\U000F054A", # mdi:umbrella
          "\U000F17FF", # mdi:sun-wireless-outline
          "\U000F0C16", # mdi:alpha-o-circle
          "\U000F00B5", # mdi:blur
          "\U000F00B6"  # mdi:blur-linear
          ]  
  - file: "fonts/DroidSansHS.ttf"
    id: weather_20
    size: 23
    bpp: 4
    glyphs: ${weather_characters}
    extras:
      - file: 'fonts/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
        glyphs: [          
          "\U000F0143", # mdi:chevron-up
          "\U000F0140",  # mdi:chevron-down
          "\U000F059C", # mdi:weather-sunset-up
          "\U000F059B"  # mdi:weather-sunset-down
          ]  

  - file: "fonts/DroidSansHS.ttf"
    id: title_font
    size: 18
    bpp: 4
    glyphs: ${title_characters}
    extras:
      - file: 'fonts/materialdesignicons-webfont.ttf' # http://materialdesignicons.com/cdn/7.4.47/ 
        glyphs: [
          "\U000F05A9", # mdi:wifi
          "\U000F16C5", # mdi:wifi-remove
          "\U000F001B", # mdi:air-conditioner
          "\U000F0F92", # mdi:water-boiler
          "\U000F1099", # mdi:air-humidifier
          "\U000F0D44", # mdi:air-purifier
          "\U000F1A73", # mdi:solar-power-variant
          "\U000F192C"  # mdi:transmission-tower-export
          ]  
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icon_font_90
    size: 90
    bpp: 4
    glyphs: [
          "\U000F0595", # mdi:weather-partly-cloudy
          "\U000F0335", # mdi:lightbulb
          "\U000F0F54", # mdi:home-thermometer
          "\U000F0439", # mdi:radio
          "\U000F1A2D", # mdi:blinds-vertical
          "\U000F07AE", # mdi:cctv
          "\U000F1A57", # mdi:meter-electric
          "\U000F081C", # mdi:door-open
          "\U000F081B", # mdi:door-closed
          "\U000F11DB", # mdi:window-closed-variant
          "\U000F11DC", # mdi:window-open-variant
          "\U000F0493", # mdi:cog
          "\U000F0425", # mdi:power
          "\U000F18F2", # mdi:mdi:refresh-auto
          "\U000F0C11", # mdi:alpha-m-circle-outline
          "\U000F04B2"  # mdi:sleep
          ]  
          
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icon_font_200
    size: 200
    bpp: 4
    glyphs: [
          "\U000F081C", # mdi:door-open
          "\U000F081B", # mdi:door-closed
          "\U000F11DB", # mdi:window-closed-variant
          "\U000F11DC" # mdi:window-open-varian       
          ]
